### ISSUE TITLE
Test R CMD check of travis branch

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsModules#11]
The [native travis branch](https://github.com/SWS-Methodology/faoswsModules/tree/native-r-travis)  keeps failing the R CMD check, but it doesn't do so on my local machine. I suspect that it may fail checks on Linux. Someone with a Linux system should confirm this.

**Comment by mkao006** [comment]
Log from Linux machine, only warnings no error.

mk@mk-IdeaPad-U330p:~/Github/sws_skeleton_project$ R CMD check faoswsModules
* using log directory ‘/home/mk/Github/sws_skeleton_project/faoswsModules.Rcheck’
* using R version 3.3.0 (2016-05-03)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘faoswsModules/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘faoswsModules’ version ‘0.1.0’
* checking package namespace information ... OK
* checking package dependencies ...^C
Execution halted

mk@mk-IdeaPad-U330p:~/Github/sws_skeleton_project$ R CMD check faoswsModules_0.1.0.tar.gz 
* using log directory ‘/home/mk/Github/sws_skeleton_project/faoswsModules.Rcheck’
* using R version 3.3.0 (2016-05-03)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘faoswsModules/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘faoswsModules’ version ‘0.1.0’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘faoswsModules’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... WARNING
Non-standard license specification:
  FAO
Standardizable: FALSE
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
CopyKey: no visible global function definition for ‘is’
writeClip: no visible global function definition for ‘writeClipboard’
Undefined global functions or variables:
  is writeClipboard
Consider adding
  importFrom("methods", "is")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

Status: 1 WARNING, 1 NOTE
See
  ‘/home/mk/Github/sws_skeleton_project/faoswsModules.Rcheck/00check.log’
for details.

**Comment by sebastian-c** [comment]
I made modifications to fix that warning and note, but it [still fails on travis](https://travis-ci.org/SWS-Methodology/faoswsModules/builds/131073134).

**Comment by sebastian-c** [comment]
I need to test this on my Ubuntu machine

**Comment by sebastian-c** [comment]
Tested, fails because the Linux version of `utils` doesn't have `writeClipboard`.
